### PR TITLE
sources migrated to tonel

### PR DESCRIPTION
**Pull request by noha**
second try

### CODE REVIEW

**Comment by seandenigris** [comment]
@noha Can you say more about the missing method issue?

**Comment by noha** [comment]
I‘m on case sensitive now. As MacOS is default case insensitive but case preserving I assumed that seitching my disk to case sensitive it removed the possibility of differentation for cases with different upoercase lowercase names. I mentioned the readonly/readOnly case. The new method just dissappears and the old one calling the new one raises the error in the tests.

**Comment by seandenigris** [comment]
@noha Are you saying you tried again on case sensitive and it did not fix the problem? There are other weird things on my branch. It reports branching from the latest commit, but the code is from an older commit. I'm going to try one more time from scratch...

**Comment by noha** [comment]
I changed the filesystem before converting magritte. So I only did case sensitive and had the impression that someone with case insensitive could convert

**Pull request closed without merging**
