### PR TITLE
- added pharo10 platform attribute section

### PR DESCRIPTION
**Pull request by noha**
- removed GT loading
- upgraded grease to 1.8

### CODE REVIEW

**Comment by seandenigris** [comment]
Thanks for this. Why did you eliminate the `Magritte-Pharo-Model` alias from the P9 spec? I'm pretty sure it's been there since before I got involved and I'm not clear about its purpose or the ramifications of changing it

**Comment by seandenigris** [comment]
I'm now seeing the following when loading Magritte. My guess is that it's related to my questions above. Any ideas @noha or @hernanmd?

**Comment by noha** [comment]
@seandenigris Which platform and version is this. I added groups for conditional loading so it is likely I messed it up

**Comment by seandenigris** [comment]
P9 & baseline I.e. no version specified which IIRC means latest commit

**Pull request merged**
