### PR TITLE
Migrate sources to tonel

### PR DESCRIPTION
**Pull request by seandenigris**

### CODE REVIEW

**Comment by seandenigris** [comment]
Making progress, @noha! Only P5 32-bit failing and may have been unrelated. Restarting job now...

**Comment by noha** [comment]
Great! Thank you @seandenigris . Yes pharo5 is quite old and supporting 3 versions is sufficient IMHO

**Comment by seandenigris** [comment]
Glad we got this done. RMOD seemed to need it because windows users were having problems

**Comment by noha** [comment]
Yes it is like with all projects that the filename can exceed the maximum of the windows filesystem

**Pull request merged**
